export const STUDENT_REQUEST = 'STUDENT_REQUEST'
export const STUDENT_GET_ALL = 'STUDENT_GET_ALL'
export const STUDENT_GET_ALL_SUCCESS = 'STUDENT_GET_ALL_SUCCESS'

export const STUDENT_GET = 'STUDENT_GET'
export const STUDENT_GET_SUCCESS = 'STUDENT_GET_SUCCESS'

export const STUDENT_UPDATE = 'STUDENT_UPDATE'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'

export const STUDENT_CREATE = 'STUDENT_CREATE'
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS'

export const STUDENT_DELETE = 'STUDENT_DELETE'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const GET_EDUCATION__FACILITY_DATA ='GET_EDUCATION__FACILITY_DATA'
export const FACILITIES_CREATE = 'FACILITIES_CREATE'
export const STUDENT_PASSWORD_UPDATE = 'STUDENT_PASSWORD_UPDATE'